// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUgocAHjZpXRx6uw6VLp7oJbrL1jqtofw',
    appId: '1:460469860911:web:1c13ab6bcbc4ea2714e4da',
    messagingSenderId: '460469860911',
    projectId: 'fruit-hub-47864',
    authDomain: 'fruit-hub-47864.firebaseapp.com',
    storageBucket: 'fruit-hub-47864.firebasestorage.app',
    measurementId: 'G-D0S8DY8D52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD61zcFJNdxwfCUpQEg1Ypet4_N98ArbWQ',
    appId: '1:460469860911:android:12715471027b5f8b14e4da',
    messagingSenderId: '460469860911',
    projectId: 'fruit-hub-47864',
    storageBucket: 'fruit-hub-47864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUBby3Zyxb-7kM6M-Ia2_v1FUL1wYjIIY',
    appId: '1:460469860911:ios:4ecfa34abfc2af5214e4da',
    messagingSenderId: '460469860911',
    projectId: 'fruit-hub-47864',
    storageBucket: 'fruit-hub-47864.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUBby3Zyxb-7kM6M-Ia2_v1FUL1wYjIIY',
    appId: '1:460469860911:ios:4ecfa34abfc2af5214e4da',
    messagingSenderId: '460469860911',
    projectId: 'fruit-hub-47864',
    storageBucket: 'fruit-hub-47864.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUgocAHjZpXRx6uw6VLp7oJbrL1jqtofw',
    appId: '1:460469860911:web:f1b692bf132ea1e114e4da',
    messagingSenderId: '460469860911',
    projectId: 'fruit-hub-47864',
    authDomain: 'fruit-hub-47864.firebaseapp.com',
    storageBucket: 'fruit-hub-47864.firebasestorage.app',
    measurementId: 'G-R8F2Q2V4KB',
  );

}